server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
  - type: http 
    port:    ${PORT:-8080}
  adminConnectors:
  - type: http
    port: 9292
swagger:
  resourcePackage: com.spx
applicationPackages:
- com.spx.containment*
- com.spx.sample2*
unsecurePaths: ['swagger','swagger.json']

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: test

  # the password
  password: password

  # the JDBC URL
  url:    ${AUTH_DB_URL:-"jdbc:postgresql://host.docker.internal/testdb"}   

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.archive.autodetection: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* M H Application Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
containment:
  database:
    user:  ${CONTAINMENT_DB_USER:-"test"}
    password: password
    url:  ${CONTAINMENT_DB_URL:-"containment-db:7687"}